# Generated by Django 2.0.3 on 2018-12-26 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arquitectura', '0007_auto_20181130_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bienvenida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=254)),
                ('fecha_envio', models.DateField(blank=True, null=True)),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arquitectura.Socio')),
            ],
        ),
    ]
