# Generated by Django 2.0.3 on 2018-12-27 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herramientas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bienvenida',
            name='saludo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
