# Generated by Django 2.0.3 on 2019-01-10 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arquitectura', '0007_auto_20181130_1243'),
        ('consorcios', '0002_consorcio_costo_mp'),
        ('herramientas', '0003_transferencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='CajaTransferencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('referencia', models.CharField(blank=True, max_length=10, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('consorcio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consorcios.Consorcio')),
                ('destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transferencia_destino', to='arquitectura.Caja')),
                ('origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transferencia_origen', to='arquitectura.Caja')),
            ],
        ),
        migrations.RemoveField(
            model_name='transferencia',
            name='caja_destino',
        ),
        migrations.RemoveField(
            model_name='transferencia',
            name='caja_origen',
        ),
        migrations.RemoveField(
            model_name='transferencia',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='transferencia',
            name='valor',
        ),
        migrations.AddField(
            model_name='transferencia',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='cajatransferencia',
            name='transferencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='herramientas.Transferencia'),
        ),
    ]
