# Generated by Django 2.0.3 on 2018-10-30 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consorcios', '0001_initial'),
        ('afip', '0003_auto_20180821_1213'),
        ('contabilidad', '0001_initial'),
        ('arquitectura', '0002_auto_20181030_1145'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CajaOP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(blank=True, max_length=10, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arquitectura.Caja')),
            ],
        ),
        migrations.CreateModel(
            name='Deuda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_carga', models.DateField(auto_now=True)),
                ('fecha', models.DateField()),
                ('numero', models.CharField(blank=True, max_length=15, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('confirmado', models.BooleanField(default=False)),
                ('pagado', models.BooleanField(default=False)),
                ('aceptado', models.BooleanField(default=True)),
                ('anulado', models.DateField(blank=True, null=True)),
                ('acreedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arquitectura.Acreedor')),
                ('asiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asiento_deuda', to='contabilidad.Asiento')),
                ('asiento_anulado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asiento_deuda_anulado', to='contabilidad.Asiento')),
                ('consorcio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consorcios.Consorcio')),
                ('retencion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='arquitectura.Relacion')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeudaOP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('deuda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='op.Deuda')),
            ],
        ),
        migrations.CreateModel(
            name='GastoDeuda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('deuda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='op.Deuda')),
                ('gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arquitectura.Gasto')),
            ],
        ),
        migrations.CreateModel(
            name='GastoOP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arquitectura.Gasto')),
            ],
        ),
        migrations.CreateModel(
            name='OP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('numero', models.PositiveIntegerField(blank=True, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('confirmado', models.BooleanField(default=False)),
                ('aceptado', models.BooleanField(default=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='op/pdf/')),
                ('anulado', models.DateField(blank=True, null=True)),
                ('acreedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arquitectura.Acreedor')),
                ('asiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asiento_op', to='contabilidad.Asiento')),
                ('asiento_anulado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asiento_op_anulado', to='contabilidad.Asiento')),
                ('consorcio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consorcios.Consorcio')),
                ('punto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afip.PointOfSales')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RetencionOP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('deuda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='op.Deuda')),
                ('op', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='op.OP')),
            ],
        ),
        migrations.AddField(
            model_name='gastoop',
            name='op',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='op.OP'),
        ),
        migrations.AddField(
            model_name='deudaop',
            name='op',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='op.OP'),
        ),
        migrations.AddField(
            model_name='cajaop',
            name='op',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='op.OP'),
        ),
    ]
