# Generated by Django 2.0.3 on 2019-04-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op', '0002_auto_20190410_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='op',
            name='fecha_operacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
