# Generated by Django 2.2.19 on 2021-06-29 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CobroExp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_consorcio', models.PositiveIntegerField(blank=True, null=True)),
                ('unidad_funcional', models.PositiveIntegerField(blank=True, null=True)),
                ('fecha_cobro', models.DateField(blank=True, null=True)),
                ('importe_cobrado', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('comision_plataforma', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('neto_a_depositar', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('canal_de_pago', models.CharField(max_length=15)),
                ('documentado', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
