# Generated by Django 2.0.3 on 2018-10-30 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icono', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=70)),
                ('slug', models.SlugField(max_length=70)),
                ('descripcion', models.TextField()),
                ('galeria', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('slug', models.SlugField(max_length=70)),
                ('ubicacion', models.FileField(upload_to='biblioteca/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.Categoria')),
                ('compartido', models.ManyToManyField(to='auth.Group')),
            ],
        ),
    ]
