# Generated by Django 2.0.3 on 2018-10-30 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('consorcios', '0001_initial'),
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='consorcio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consorcios.Consorcio'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='compartido',
            field=models.ManyToManyField(to='auth.Group'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='consorcio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consorcios.Consorcio'),
        ),
    ]
