# Generated by Django 2.0.3 on 2018-10-30 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consorcios', '0001_initial'),
        ('afip', '0003_auto_20180821_1213'),
        ('contabilidad', '0001_initial'),
        ('arquitectura', '0002_auto_20181030_1145'),
        ('comprobantes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='saldo',
            name='consorcio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consorcios.Consorcio'),
        ),
        migrations.AddField(
            model_name='saldo',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijos', to='comprobantes.Saldo'),
        ),
        migrations.AddField(
            model_name='saldo',
            name='socio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arquitectura.Socio'),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='asiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contabilidad.Asiento'),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='consorcio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consorcios.Consorcio'),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='afip.Receipt'),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='relacionado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comprobantes.Comprobante'),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='socio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arquitectura.Socio'),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compensacion',
            name='asiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contabilidad.Asiento'),
        ),
        migrations.AddField(
            model_name='compensacion',
            name='comprobante_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compensacion_comprobante_destino', to='comprobantes.Comprobante'),
        ),
        migrations.AddField(
            model_name='compensacion',
            name='comprobante_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compensacion_comprobante_origen', to='comprobantes.Comprobante'),
        ),
        migrations.AddField(
            model_name='compensacion',
            name='consorcio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consorcios.Consorcio'),
        ),
    ]
