# Generated by Django 2.0.3 on 2018-11-07 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('afip', '0003_auto_20180821_1213'),
        ('arquitectura', '0003_auto_20181106_1834'),
        ('consorcios', '0001_initial'),
        ('contabilidad', '0001_initial'),
        ('comprobantes', '0003_auto_20181030_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprobante',
            name='confirmado',
        ),
        migrations.RemoveField(
            model_name='comprobante',
            name='usuario',
        ),
        migrations.AddField(
            model_name='cajacomprobante',
            name='consorcio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='consorcios.Consorcio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cajacomprobante',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cajacomprobante',
            name='socio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arquitectura.Socio'),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='anulado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='asiento_anulado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asiento_comp_anulado', to='contabilidad.Asiento'),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='nota_credito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nota_credito', to='afip.Receipt'),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='nota_debito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nota_debito', to='afip.Receipt'),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='numero',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='pdf_nota_credito',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes/pdf/'),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='pdf_nota_debito',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes/pdf/'),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='punto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='afip.PointOfSales'),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comprobante', to='afip.Receipt'),
        ),
    ]
