# Generated by Django 2.0.3 on 2018-11-10 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobantes', '0004_auto_20181107_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobante',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
