# Generated by Django 2.0.3 on 2018-11-12 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comprobantes', '0005_comprobante_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprobante',
            name='pdf_nota_credito',
        ),
        migrations.RemoveField(
            model_name='comprobante',
            name='pdf_nota_debito',
        ),
    ]
