# Generated by Django 2.0.3 on 2018-11-26 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('afip', '0003_auto_20180821_1213'),
        ('comprobantes', '0009_auto_20181115_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobante',
            name='nota_credito_anulado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nota_credito_anulado', to='afip.Receipt'),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='nota_debito_anulado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nota_debito_anulado', to='afip.Receipt'),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='pdf_anulado',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes/pdf/'),
        ),
    ]
