# Generated by Django 2.0.3 on 2018-11-26 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comprobantes', '0010_auto_20181126_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobante',
            name='asiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comprobante_original', to='contabilidad.Asiento'),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='asiento_anulado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comprobante_anulado', to='contabilidad.Asiento'),
        ),
    ]
