# Generated by Django 2.0.3 on 2018-10-30 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('afip', '0003_auto_20180821_1213'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mp', '0018_auto_20180808_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codigo_Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('codigo_afip', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Consorcio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('nombre_completo', models.CharField(max_length=70)),
                ('abreviatura', models.CharField(max_length=7)),
                ('domicilio', models.CharField(blank=True, max_length=70, null=True)),
                ('superficie', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('fecha_reg', models.DateTimeField(auto_now_add=True)),
                ('mails', models.BooleanField(default=False)),
                ('dominioweb', models.CharField(blank=True, max_length=70, null=True)),
                ('contribuyente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afip.TaxPayer')),
                ('mercado_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mp.Account')),
                ('provincia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consorcios.Codigo_Provincia')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_CU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('codigo_afip', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Ocupante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('codigo_afip', models.CharField(max_length=4)),
            ],
        ),
        migrations.AddField(
            model_name='consorcio',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consorcios.Tipo_CU'),
        ),
        migrations.AddField(
            model_name='consorcio',
            name='usuarios',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
