# Generated by Django 2.2.19 on 2023-11-09 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consorcios', '0002_consorcio_costo_mp'),
    ]

    operations = [
        migrations.AddField(
            model_name='consorcio',
            name='cuit_nasociado',
            field=models.BooleanField(default=False),
        ),
    ]
