# Generated by Django 2.0.3 on 2020-08-27 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consorcios', '0002_consorcio_costo_mp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteSS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('expensas_pagas', models.BooleanField(default=False)),
                ('consorcio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ss', to='consorcios.Consorcio')),
            ],
        ),
        migrations.CreateModel(
            name='Enviado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=20)),
                ('id_modelo', models.PositiveIntegerField()),
                ('fecha_envio', models.DateField(blank=True, null=True)),
                ('consorcio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consorcios.Consorcio')),
            ],
        ),
    ]
