# Generated by Django 2.0.3 on 2018-10-30 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consorcios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asiento', models.DateField()),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_ultima_modificacion', models.DateField(auto_now=True)),
                ('principal', models.IntegerField(blank=True, null=True)),
                ('consorcio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consorcios.Consorcio')),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.IntegerField()),
                ('numero', models.CharField(max_length=6)),
                ('nombre', models.CharField(max_length=50)),
                ('consorcio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consorcios.Consorcio')),
                ('dependencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contabilidad.Cuenta')),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_aleatorio', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=15)),
                ('inicio', models.DateField()),
                ('cierre', models.DateField()),
                ('activo', models.BooleanField(default=False)),
                ('consorcio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consorcios.Consorcio')),
            ],
        ),
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_aleatorio', models.CharField(blank=True, max_length=30, null=True)),
                ('debe', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('haber', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.Cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consorcio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consorcios.Consorcio')),
                ('cuentas', models.ManyToManyField(to='contabilidad.Cuenta')),
            ],
        ),
        migrations.AddField(
            model_name='asiento',
            name='operaciones',
            field=models.ManyToManyField(to='contabilidad.Operacion'),
        ),
    ]
