# Generated by Django 2.0.3 on 2018-10-30 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('creditos', '0001_initial'),
        ('consorcios', '0001_initial'),
        ('contabilidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cierre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_aleatorio', models.CharField(blank=True, max_length=30, null=True)),
                ('periodo', models.DateField()),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('per_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('referencia', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('reservado', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('confirmado', models.BooleanField(default=False)),
                ('consorcio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consorcios.Consorcio')),
                ('liquidacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='creditos.Liquidacion')),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_aleatorio', models.CharField(blank=True, max_length=30, null=True)),
                ('ubicacion', models.FileField(upload_to='reportes/')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('automatico', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subtotal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('numero_aleatorio', models.CharField(blank=True, max_length=30, null=True)),
                ('cuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contabilidad.Cuenta')),
            ],
        ),
        migrations.AddField(
            model_name='cierre',
            name='reportes',
            field=models.ManyToManyField(blank=True, to='reportes.Reporte'),
        ),
        migrations.AddField(
            model_name='cierre',
            name='subtotales',
            field=models.ManyToManyField(to='reportes.Subtotal'),
        ),
    ]
