# Generated by Django 2.0.3 on 2018-11-29 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consorcios', '0002_consorcio_costo_mp'),
        ('reportes', '0002_auto_20181127_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='consorcio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consorcios.Consorcio'),
        ),
    ]
