# Generated by Django 2.0.3 on 2018-11-30 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0003_reporte_consorcio'),
    ]

    operations = [
        migrations.AddField(
            model_name='cierre',
            name='auditor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cierre',
            name='logo_auditor',
            field=models.FileField(blank=True, null=True, upload_to='reportes/logos/'),
        ),
    ]
