# Generated by Django 2.0.3 on 2018-12-07 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0006_cierre_mails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cierre',
            name='auditor',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
