# Generated by Django 2.0.3 on 2018-10-30 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('creditos', '0001_initial'),
        ('arquitectura', '0002_auto_20181030_1145'),
        ('mp', '0018_auto_20180808_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capital', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('int_desc', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('credito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='creditos.Credito')),
                ('preference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mp.Preference')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arquitectura.Socio')),
            ],
        ),
    ]
