# Generated by Django 2.0.3 on 2018-10-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resumen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('slug', models.SlugField(blank=True, max_length=70, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
