# Generated by Django 2.0.3 on 2018-11-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0004_auto_20181103_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacion',
            name='mails',
            field=models.BooleanField(default=False),
        ),
    ]
