# Generated by Django 2.0.3 on 2019-01-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0006_credito_detalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='detalle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
