# Generated by Django 2.0.3 on 2018-10-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accesorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('plazo', models.PositiveIntegerField(blank=True, null=True)),
                ('clase', models.CharField(choices=[('interes', 'Interes'), ('descuento', 'Descuento')], max_length=15)),
                ('tipo', models.CharField(choices=[('fijo', 'Monto fijo'), ('tasa', 'Tasa')], default='tasa', max_length=15)),
                ('monto', models.IntegerField(blank=True, null=True)),
                ('base_calculo', models.IntegerField(choices=[(1, 'Diario'), (7, 'Semanal'), (15, 'Quincenal'), (30, 'Mensual'), (60, 'Bimestral'), (90, 'Trimestral'), (120, 'Semestral')], default=30)),
                ('condicion', models.CharField(blank=True, choices=[(None, 'Sin condicion'), ('grupo', 'Pertenencia a un grupo')], max_length=15, null=True)),
                ('finalizacion', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Acreedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primario', models.BooleanField(default=False)),
                ('nombre', models.CharField(max_length=150)),
                ('numero_documento', models.CharField(blank=True, max_length=13, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primario', models.BooleanField(default=False)),
                ('nombre', models.CharField(max_length=30)),
                ('entidad', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dominio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=5)),
                ('superficie_total', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('superficie_cubierta', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('domicilio_calle', models.CharField(blank=True, max_length=70, null=True)),
                ('domicilio_numero', models.CharField(blank=True, max_length=10, null=True)),
                ('domicilio_piso', models.CharField(blank=True, max_length=10, null=True)),
                ('domicilio_oficina', models.CharField(blank=True, max_length=10, null=True)),
                ('domicilio_sector', models.CharField(blank=True, max_length=10, null=True)),
                ('domicilio_torre', models.CharField(blank=True, max_length=10, null=True)),
                ('domicilio_manzana', models.CharField(blank=True, max_length=10, null=True)),
                ('domicilio_parcela', models.CharField(blank=True, max_length=10, null=True)),
                ('domicilio_catastro', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'ordering': ['socio'],
            },
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primario', models.BooleanField(default=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primario', models.BooleanField(default=False)),
                ('nombre', models.CharField(max_length=30)),
                ('prorrateo', models.BooleanField(default=False)),
                ('prioritario', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Relacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_socio', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=80)),
                ('apellido', models.CharField(max_length=80)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('es_extranjero', models.BooleanField(default=False)),
                ('numero_documento', models.CharField(blank=True, max_length=13, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('domicilio', models.CharField(blank=True, max_length=100, null=True)),
                ('localidad', models.CharField(blank=True, max_length=100, null=True)),
                ('profesion', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'ordering': ['apellido'],
            },
        ),
    ]
