# Generated by Django 2.0.3 on 2018-10-30 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consorcios', '0001_initial'),
        ('afip', '0003_auto_20180821_1213'),
        ('contabilidad', '0001_initial'),
        ('arquitectura', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='consorcio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consorcios.Consorcio'),
        ),
        migrations.AddField(
            model_name='socio',
            name='provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consorcios.Codigo_Provincia'),
        ),
        migrations.AddField(
            model_name='socio',
            name='tipo_documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='afip.DocumentType'),
        ),
        migrations.AddField(
            model_name='socio',
            name='usuarios',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='relacion',
            name='cuenta_contable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.Cuenta'),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='consorcio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consorcios.Consorcio'),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='cuenta_contable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.Cuenta'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='consorcio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consorcios.Consorcio'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='dominios',
            field=models.ManyToManyField(to='arquitectura.Dominio'),
        ),
        migrations.AddField(
            model_name='gasto',
            name='consorcio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consorcios.Consorcio'),
        ),
        migrations.AddField(
            model_name='gasto',
            name='cuenta_contable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.Cuenta'),
        ),
        migrations.AddField(
            model_name='dominio',
            name='consorcio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consorcios.Consorcio'),
        ),
        migrations.AddField(
            model_name='dominio',
            name='identificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consorcios.Tipo_Ocupante'),
        ),
        migrations.AddField(
            model_name='dominio',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijos', to='arquitectura.Dominio'),
        ),
        migrations.AddField(
            model_name='dominio',
            name='propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propietario', to='arquitectura.Socio'),
        ),
        migrations.AddField(
            model_name='dominio',
            name='socio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='socio', to='arquitectura.Socio'),
        ),
        migrations.AddField(
            model_name='caja',
            name='consorcio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consorcios.Consorcio'),
        ),
        migrations.AddField(
            model_name='caja',
            name='cuenta_contable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.Cuenta'),
        ),
        migrations.AddField(
            model_name='acreedor',
            name='consorcio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consorcios.Consorcio'),
        ),
        migrations.AddField(
            model_name='acreedor',
            name='cuenta_contable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.Cuenta'),
        ),
        migrations.AddField(
            model_name='acreedor',
            name='genera',
            field=models.ManyToManyField(blank=True, related_name='genera', to='arquitectura.Relacion'),
        ),
        migrations.AddField(
            model_name='acreedor',
            name='recibe',
            field=models.ManyToManyField(blank=True, related_name='recibe', to='arquitectura.Relacion'),
        ),
        migrations.AddField(
            model_name='acreedor',
            name='tipo',
            field=models.ManyToManyField(to='arquitectura.Gasto'),
        ),
        migrations.AddField(
            model_name='acreedor',
            name='tipo_documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='afip.DocumentType'),
        ),
        migrations.AddField(
            model_name='accesorio',
            name='consorcio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consorcios.Consorcio'),
        ),
        migrations.AddField(
            model_name='accesorio',
            name='cuenta_contable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.Cuenta'),
        ),
        migrations.AddField(
            model_name='accesorio',
            name='ingreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='arquitectura.Ingreso'),
        ),
        migrations.AlterUniqueTogether(
            name='dominio',
            unique_together={('consorcio', 'numero')},
        ),
    ]
