# Generated by Django 2.0.3 on 2018-11-06 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquitectura', '0002_auto_20181030_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesorio',
            name='clase',
            field=models.CharField(choices=[('interes', 'Interes'), ('descuento', 'Descuento'), ('bonificacion', 'Bonificacion')], max_length=15),
        ),
    ]
