# Generated by Django 2.0.3 on 2018-11-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquitectura', '0003_auto_20181106_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='baja',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='codigo',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
