# Generated by Django 2.0.3 on 2018-11-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquitectura', '0004_auto_20181120_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='baja',
            field=models.DateField(blank=True, null=True),
        ),
    ]
