# Generated by Django 2.0.3 on 2018-11-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquitectura', '0006_accesorio_reconocimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesorio',
            name='ingreso',
        ),
        migrations.AddField(
            model_name='accesorio',
            name='ingreso',
            field=models.ManyToManyField(blank=True, to='arquitectura.Ingreso'),
        ),
    ]
