# Generated by Django 2.2.19 on 2021-06-30 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquitectura', '0008_auto_20201022_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
