# Generated by Django 2.2.19 on 2022-05-01 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
        ('consorcios', '0002_consorcio_costo_mp'),
        ('arquitectura', '0009_socio_mail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_asociado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('baja', models.DateField(blank=True, null=True)),
                ('consorcio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_asociado', to='consorcios.Consorcio')),
            ],
        ),
        migrations.CreateModel(
            name='Servicios_mutuales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.TextField()),
                ('baja', models.DateField(blank=True, null=True)),
                ('grupo_asociados', models.CharField(max_length=80)),
                ('consorcio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_mutuales', to='consorcios.Consorcio')),
                ('cuenta_contable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.Cuenta')),
            ],
        ),
    ]
