# Generated by Django 2.2.19 on 2022-05-01 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquitectura', '0010_servicios_mutuales_tipo_asociado'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='fecha_alta',
            field=models.DateField(blank=True, null=True),
        ),
    ]
