# Generated by Django 2.2.19 on 2022-05-01 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arquitectura', '0011_socio_fecha_alta'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='tipo_asociado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='socio', to='arquitectura.Tipo_asociado'),
        ),
    ]
