# Generated by Django 2.2.19 on 2022-05-01 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquitectura', '0012_socio_tipo_asociado'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='notificaciones',
            field=models.BooleanField(default=False),
        ),
    ]
