# Generated by Django 2.2.19 on 2022-05-06 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquitectura', '0014_socio_numero_asociado'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_asociado',
            name='descripcion',
            field=models.TextField(null=True),
        ),
    ]
