# Generated by Django 2.2.19 on 2022-05-06 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
        ('consorcios', '0002_consorcio_costo_mp'),
        ('arquitectura', '0015_tipo_asociado_descripcion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Servicios_mutuales',
            new_name='Servicio_mutuales',
        ),
    ]
