# Generated by Django 2.2.19 on 2022-05-06 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquitectura', '0016_auto_20220506_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio_mutuales',
            name='grupo_asociados',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
