# Generated by Django 2.2.19 on 2022-05-06 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consorcios', '0002_consorcio_costo_mp'),
        ('contabilidad', '0001_initial'),
        ('arquitectura', '0017_auto_20220506_1906'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Servicio_mutuales',
            new_name='Servicio_mutual',
        ),
    ]
