# Generated by Django 2.2.19 on 2022-05-10 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
        ('arquitectura', '0019_auto_20220509_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='cuenta_contable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contabilidad.Cuenta'),
        ),
        migrations.AddField(
            model_name='socio',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='nombre_servicio_mutual',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.DeleteModel(
            name='Servicio_mutual',
        ),
    ]
