# Generated by Django 2.2.19 on 2022-05-11 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquitectura', '0021_remove_socio_cuenta_contable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='nombre',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
