# Generated by Django 2.2.19 on 2023-09-04 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquitectura', '0023_servicio_mutual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio_mutual',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
