# Generated by Django 2.2.19 on 2023-09-04 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquitectura', '0024_auto_20230904_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio_mutual',
            name='descripcion',
            field=models.TextField(max_length=400, null=True),
        ),
    ]
