# Generated by Django 2.2.19 on 2023-09-04 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquitectura', '0026_auto_20230904_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio_mutual',
            name='baja',
            field=models.DateField(blank=True, null=True),
        ),
    ]
