# Generated by Django 2.2.19 on 2023-09-11 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquitectura', '0027_servicio_mutual_baja'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='calle',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='causa_baja',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='cuit',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='departamento',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='medida_disciplinaria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='numero_calle',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='observacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='piso',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='tipo_persona',
            field=models.CharField(choices=[('fisica', 'Fisica'), ('juridica', 'Juridica')], default='fisica', max_length=15),
        ),
    ]
