# Generated by Django 2.2.19 on 2023-09-11 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arquitectura', '0028_auto_20230911_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socio',
            name='calle',
        ),
    ]
