# Generated by Django 2.2.19 on 2023-10-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquitectura', '0029_remove_socio_calle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio_mutual',
            name='descripcion',
            field=models.TextField(max_length=5000, null=True),
        ),
    ]
