# Generated by Django 2.2.19 on 2023-10-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquitectura', '0031_auto_20231021_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio_mutual',
            name='descripcion',
            field=models.TextField(max_length=20000, null=True),
        ),
    ]
