# Generated by Django 2.2.19 on 2023-10-23 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquitectura', '0033_auto_20231023_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='numero_asociado',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
