# Generated by Django 2.2.19 on 2023-10-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquitectura', '0034_auto_20231023_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio_mutual',
            name='descripcion',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='servicio_mutual',
            name='nombre_reglamento',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
