# Generated by Django 2.2.19 on 2023-10-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquitectura', '0035_auto_20231023_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='numero_asociado',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
