# Generated by Django 2.2.19 on 2023-11-07 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquitectura', '0037_tipo_asociado_cuota_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='directivo',
            field=models.CharField(blank=True, choices=[('presidente', 'Presidente'), ('secretario', 'Secretario'), ('tesorero', 'Tesorero'), ('primer_vocal', 'Primer Vocal'), ('segundo_vocal', 'Segundo Vocal'), ('tercer_vocal', 'Tercer Vocal'), ('primer_vocal_suplente', 'Primer Vocal Suplente'), ('segundo_vocal', 'Segundo Vocal Suplente'), ('tercer_vocal', 'Tercer Vocal Suplente')], max_length=20, null=True),
        ),
    ]
