# Generated by Django 2.2.19 on 2023-11-07 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquitectura', '0038_socio_directivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='estado',
            field=models.CharField(blank=True, choices=[('vigente', 'Vigente'), ('baja', 'Baja'), ('suspendido', 'Suspendido')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='socio',
            name='directivo',
            field=models.CharField(blank=True, choices=[('presidente', 'Presidente'), ('secretario', 'Secretario'), ('prosecretario', 'Pro Secretario'), ('tesorero', 'Tesorero'), ('protesorero', 'Pro Tesorero'), ('vicepresidente', 'Vicepresidente'), ('primer_vocal', 'Vocal Titular Primero'), ('segundo_vocal', 'Vocal Titular Segundo'), ('tercer_vocal', 'Vocal Titular Tercero'), ('cuarto_vocal', 'Vocal Titular Cuarto'), ('primer_vocal_suplente', 'Vocal Suplente Primero'), ('segundo_vocal_suplente', 'Vocal Suplente Segundo'), ('tercer_vocal_suplente', 'Vocal Suplente Tercero'), ('cuarto_vocal_suplente', 'Vocal Suplente Cuarto'), ('Revisor_cuenta_1ro', 'Junta Fiscalizadora, Revisor de cuenta primero'), ('Revisor_cuenta_1ro_suplente', 'Junta Fiscalizadora, Revisor de cuenta primero suplente'), ('Revisor_cuenta_2do', 'Junta Fiscalizadora, Revisor de cuenta segundo'), ('Revisor_cuenta_2do_suplente', 'Junta Fiscalizadora, Revisor de cuenta segundo suplente'), ('Revisor_cuenta_3er', 'Junta Fiscalizadora, Revisor de cuenta tercero'), ('Revisor_cuenta_3er_suplente', 'Junta Fiscalizadora, Revisor de cuenta segundo suplente'), ('Titular_1ero', 'Junta Fiscalizadora, Titular Primero'), ('Titular_2do', 'Junta Fiscalizadora, Titular Segundo'), ('Titular_3ero', 'Junta Fiscalizadora, Titular Tercero'), ('Titular_4to', 'Junta Fiscalizadora, Titular Cuarto'), ('Suplente_1ero', 'Junta Fiscalizadora, Suplente Primero'), ('Suplente_2do', 'Junta Fiscalizadora, Suplente Segundo'), ('Suplente_3ero', 'Junta Fiscalizadora, Suplente Tercero'), ('Suplente_4to', 'Junta Fiscalizadora, Suplente Cuarto')], max_length=20, null=True),
        ),
    ]
